fixed the indent for check file

diff --git a/.github/workflows/deploy-customers.yaml b/.github/workflows/deploy-customers.yaml
--- a/.github/workflows/deploy-customers.yaml
+++ b/.github/workflows/deploy-customers.yaml
@@ -21,14 +21,14 @@ jobs:
         uses: actions/checkout@v3
       
       - name: Check if file exists
-      id: check_file
-      run: |
-        if [ ! -f ".github/artifacts/customer/customer-kong.yaml" ]; then
-          echo "Artifact file not found! Stopping workflow.. Run the build workflow before deploy !"
-          exit 1  # Exit with error if file does not exist
-        else
-          echo "Artifact file exists!"
-        fi
+        id: check_file
+        run: |
+          if [ ! -f ".github/artifacts/customer/customer-kong.yaml" ]; then
+            echo "Artifact file not found! Stopping workflow.. Run the build workflow before deploy !"
+            exit 1  # Exit with error if file does not exist
+          else
+            echo "Artifact file exists!"
+          fi
 
       - name: Setup deck
         uses: kong/setup-deck@v1
